services:
  - type: web
    name: multi-sensors-backend
    runtime: python
    plan: free
    region: oregon
    branch: main
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
